name: Playwright Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # report machine parameters
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: yarn types
      - run: yarn lint
      - run: yarn test:unit:ci
      - run: yarn start:ci
      
      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root